config/routes.rb
Rails.application.routes.draw do
  resources :bottles
  resources :perfumes
  resources :bottle_types
  resources :perfume_types
  resources :family_types

  get '/', :to => 'static#home'
  root 'static#home'

  namespace :api, defaults: { format: 'json' } do
  	namespace :v1 do
  	  resources :bottles, only: [:create, :update, :show, :index]
      resources :perfumes, only: [:create, :update, :show, :index]
      resources :bottle_types, only: [:create, :update, :show, :index]
      resources :perfume_types, only: [:create, :update, :show, :index]
      resources :family_types, only: [:create, :update, :show, :index]
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/api/v1/bottle_types_controller.rb
module API
  module V1
    class BottleTypesController < ApiController
      before_action :set_bottle_type, only: [:show, :edit, :update, :destroy]

      # GET /bottle_types
      # GET /bottle_types.json
      def index
        @bottle_types = BottleType.all
      end

      # GET /bottle_types/1
      # GET /bottle_types/1.json
      def show
      end

      # GET /bottle_types/new
      def new
        @bottle_type = BottleType.new
      end

      # GET /bottle_types/1/edit
      def edit
      end

      # POST /bottle_types
      # POST /bottle_types.json
      def create
        @bottle_type = BottleType.new(bottle_type_params)

        respond_to do |format|
          if @bottle_type.save
            format.html { redirect_to @bottle_type, notice: 'Bottle type was successfully created.' }
            format.json { render :show, status: :created, location: @bottle_type }
          else
            format.html { render :new }
            format.json { render json: @bottle_type.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /bottle_types/1
      # PATCH/PUT /bottle_types/1.json
      def update
        respond_to do |format|
          if @bottle_type.update(bottle_type_params)
            format.html { redirect_to @bottle_type, notice: 'Bottle type was successfully updated.' }
            format.json { render :show, status: :ok, location: @bottle_type }
          else
            format.html { render :edit }
            format.json { render json: @bottle_type.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /bottle_types/1
      # DELETE /bottle_types/1.json
      def destroy
        @bottle_type.destroy
        respond_to do |format|
          format.html { redirect_to bottle_types_url, notice: 'Bottle type was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_bottle_type
          @bottle_type = BottleType.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def bottle_type_params
          params.require(:bottle_type).permit(:name)
        end
    end
  end
end

app/controllers/bottle_types_controller.rb
class BottleTypesController < ApplicationController
  before_action :set_bottle_type, only: [:show, :edit, :update, :destroy]

  # GET /bottle_types
  # GET /bottle_types.json
  def index
    @bottle_types = BottleType.all
  end

  # GET /bottle_types/1
  # GET /bottle_types/1.json
  def show
  end

  # GET /bottle_types/new
  def new
    @bottle_type = BottleType.new
  end

  # GET /bottle_types/1/edit
  def edit
  end

  # POST /bottle_types
  # POST /bottle_types.json
  def create
    @bottle_type = BottleType.new(bottle_type_params)

    respond_to do |format|
      if @bottle_type.save
        format.html { redirect_to @bottle_type, notice: 'Bottle type was successfully created.' }
        format.json { render :show, status: :created, location: @bottle_type }
      else
        format.html { render :new }
        format.json { render json: @bottle_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bottle_types/1
  # PATCH/PUT /bottle_types/1.json
  def update
    respond_to do |format|
      if @bottle_type.update(bottle_type_params)
        format.html { redirect_to @bottle_type, notice: 'Bottle type was successfully updated.' }
        format.json { render :show, status: :ok, location: @bottle_type }
      else
        format.html { render :edit }
        format.json { render json: @bottle_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bottle_types/1
  # DELETE /bottle_types/1.json
  def destroy
    @bottle_type.destroy
    respond_to do |format|
      format.html { redirect_to bottle_types_url, notice: 'Bottle type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bottle_type
      @bottle_type = BottleType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bottle_type_params
      params.require(:bottle_type).permit(:name)
    end
end

app/helpers/bottle_types_helper.rb
module BottleTypesHelper
end

app/views/bottle_types/_form.html.haml
= form_for @bottle_type do |f|
  - if @bottle_type.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bottle_type.errors.count, "error")} prohibited this bottle_type from being saved:"
      %ul
        - @bottle_type.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/bottle_types/edit.html.haml
%h1 Editing bottle_type

= render 'form'

= link_to 'Show', @bottle_type
\|
= link_to 'Back', bottle_types_path

app/views/bottle_types/index.html.haml
%h1 Listing bottle_types

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @bottle_types.each do |bottle_type|
      %tr
        %td= bottle_type.name
        %td= link_to 'Show', bottle_type
        %td= link_to 'Edit', edit_bottle_type_path(bottle_type)
        %td= link_to 'Destroy', bottle_type, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Bottle type', new_bottle_type_path

app/views/bottle_types/new.html.haml
%h1 New bottle_type

= render 'form'

= link_to 'Back', bottle_types_path

app/views/bottle_types/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @bottle_type.name

= link_to 'Edit', edit_bottle_type_path(@bottle_type)
\|
= link_to 'Back', bottle_types_path