config/routes.rb
Rails.application.routes.draw do
  resources :bottles
  resources :perfumes
  resources :bottle_types
  resources :perfume_types
  resources :family_types

  get '/', :to => 'static#home'
  root 'static#home'

  namespace :api, defaults: { format: 'json' } do
  	namespace :v1 do
  	  resources :bottles, only: [:create, :update, :show, :index]
      resources :perfumes, only: [:create, :update, :show, :index]
      resources :bottle_types, only: [:create, :update, :show, :index]
      resources :perfume_types, only: [:create, :update, :show, :index]
      resources :family_types, only: [:create, :update, :show, :index]
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bottle.rb
class Bottle < ApplicationRecord
	belongs_to :bottle_type
end

app/models/bottle_type.rb
class BottleType < ApplicationRecord
	has_many :bottles
end

app/controllers/api/v1/bottles_controller.rb
module API
  module V1
    class BottlesController < ApiController
      before_action :set_bottle, only: [:show, :edit, :update, :destroy]

      # GET /bottles
      # GET /bottles.json
      def index
        @bottles = Bottle.all
      end

      # GET /bottles/1
      # GET /bottles/1.json
      def show
      end

      # GET /bottles/new
      def new
        @bottle = Bottle.new
      end

      # GET /bottles/1/edit
      def edit
      end

      # POST /bottles
      # POST /bottles.json
      def create
        @bottle = Bottle.new(bottle_params)

        respond_to do |format|
          if @bottle.save
            format.html { redirect_to @bottle, notice: 'Bottle was successfully created.' }
            format.json { render :show, status: :created, location: @bottle }
          else
            format.html { render :new }
            format.json { render json: @bottle.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /bottles/1
      # PATCH/PUT /bottles/1.json
      def update
        respond_to do |format|
          if @bottle.update(bottle_params)
            format.html { redirect_to @bottle, notice: 'Bottle was successfully updated.' }
            format.json { render :show, status: :ok, location: @bottle }
          else
            format.html { render :edit }
            format.json { render json: @bottle.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /bottles/1
      # DELETE /bottles/1.json
      def destroy
        @bottle.destroy
        respond_to do |format|
          format.html { redirect_to bottles_url, notice: 'Bottle was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_bottle
          @bottle = Bottle.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def bottle_params
          params.require(:bottle).permit(:name, :bottle_type_id)
        end
    end
  end
end

app/controllers/bottles_controller.rb
class BottlesController < ApplicationController
  before_action :set_bottle, only: [:show, :edit, :update, :destroy]

  # GET /bottles
  # GET /bottles.json
  def index
    @bottles = Bottle.all
  end

  # GET /bottles/1
  # GET /bottles/1.json
  def show
  end

  # GET /bottles/new
  def new
    @bottle = Bottle.new
  end

  # GET /bottles/1/edit
  def edit
  end

  # POST /bottles
  # POST /bottles.json
  def create
    @bottle = Bottle.new(bottle_params)

    respond_to do |format|
      if @bottle.save
        format.html { redirect_to @bottle, notice: 'Bottle was successfully created.' }
        format.json { render :show, status: :created, location: @bottle }
      else
        format.html { render :new }
        format.json { render json: @bottle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bottles/1
  # PATCH/PUT /bottles/1.json
  def update
    respond_to do |format|
      if @bottle.update(bottle_params)
        format.html { redirect_to @bottle, notice: 'Bottle was successfully updated.' }
        format.json { render :show, status: :ok, location: @bottle }
      else
        format.html { render :edit }
        format.json { render json: @bottle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bottles/1
  # DELETE /bottles/1.json
  def destroy
    @bottle.destroy
    respond_to do |format|
      format.html { redirect_to bottles_url, notice: 'Bottle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bottle
      @bottle = Bottle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bottle_params
      params.require(:bottle).permit(:name, :bottle_type_id)
    end
end

app/helpers/bottles_helper.rb
module BottlesHelper
end

app/views/bottles/_form.html.haml
= form_for @bottle do |f|
  - if @bottle.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bottle.errors.count, "error")} prohibited this bottle from being saved:"
      %ul
        - @bottle.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :bottle_type_id
    = f.number_field :bottle_type_id
  .actions
    = f.submit 'Save'

app/views/bottles/edit.html.haml
%h1 Editing bottle

= render 'form'

= link_to 'Show', @bottle
\|
= link_to 'Back', bottles_path

app/views/bottles/index.html.haml
%h1 Listing bottles

%table
  %thead
    %tr
      %th Name
      %th Bottle type
      %th
      %th
      %th

  %tbody
    - @bottles.each do |bottle|
      %tr
        %td= bottle.name
        %td= bottle.bottle_type_id
        %td= link_to 'Show', bottle
        %td= link_to 'Edit', edit_bottle_path(bottle)
        %td= link_to 'Destroy', bottle, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Bottle', new_bottle_path

app/views/bottles/new.html.haml
%h1 New bottle

= render 'form'

= link_to 'Back', bottles_path

app/views/bottles/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @bottle.name
%p
  %b Bottle type:
  = @bottle.bottle_type_id

= link_to 'Edit', edit_bottle_path(@bottle)
\|
= link_to 'Back', bottles_path