config/routes.rb
Rails.application.routes.draw do
  resources :bottles
  resources :perfumes
  resources :bottle_types
  resources :perfume_types
  resources :family_types

  get '/', :to => 'static#home'
  root 'static#home'

  namespace :api, defaults: { format: 'json' } do
  	namespace :v1 do
  	  resources :bottles, only: [:create, :update, :show, :index]
      resources :perfumes, only: [:create, :update, :show, :index]
      resources :bottle_types, only: [:create, :update, :show, :index]
      resources :perfume_types, only: [:create, :update, :show, :index]
      resources :family_types, only: [:create, :update, :show, :index]
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/api/v1/family_types_controller.rb
module API
  module V1
    class FamilyTypesController < ApiController
      before_action :set_family_type, only: [:show, :edit, :update, :destroy]

      # GET /family_types
      # GET /family_types.json
      def index
        @family_types = FamilyType.all
      end

      # GET /family_types/1
      # GET /family_types/1.json
      def show
      end

      # GET /family_types/new
      def new
        @family_type = FamilyType.new
      end

      # GET /family_types/1/edit
      def edit
      end

      # POST /family_types
      # POST /family_types.json
      def create
        @family_type = FamilyType.new(family_type_params)

        respond_to do |format|
          if @family_type.save
            format.html { redirect_to @family_type, notice: 'Family type was successfully created.' }
            format.json { render :show, status: :created, location: @family_type }
          else
            format.html { render :new }
            format.json { render json: @family_type.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /family_types/1
      # PATCH/PUT /family_types/1.json
      def update
        respond_to do |format|
          if @family_type.update(family_type_params)
            format.html { redirect_to @family_type, notice: 'Family type was successfully updated.' }
            format.json { render :show, status: :ok, location: @family_type }
          else
            format.html { render :edit }
            format.json { render json: @family_type.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /family_types/1
      # DELETE /family_types/1.json
      def destroy
        @family_type.destroy
        respond_to do |format|
          format.html { redirect_to family_types_url, notice: 'Family type was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_family_type
          @family_type = FamilyType.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def family_type_params
          params.require(:family_type).permit(:name)
        end
    end
  end
end

app/controllers/family_types_controller.rb
class FamilyTypesController < ApplicationController
  before_action :set_family_type, only: [:show, :edit, :update, :destroy]

  # GET /family_types
  # GET /family_types.json
  def index
    @family_types = FamilyType.all
  end

  # GET /family_types/1
  # GET /family_types/1.json
  def show
  end

  # GET /family_types/new
  def new
    @family_type = FamilyType.new
  end

  # GET /family_types/1/edit
  def edit
  end

  # POST /family_types
  # POST /family_types.json
  def create
    @family_type = FamilyType.new(family_type_params)

    respond_to do |format|
      if @family_type.save
        format.html { redirect_to @family_type, notice: 'Family type was successfully created.' }
        format.json { render :show, status: :created, location: @family_type }
      else
        format.html { render :new }
        format.json { render json: @family_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /family_types/1
  # PATCH/PUT /family_types/1.json
  def update
    respond_to do |format|
      if @family_type.update(family_type_params)
        format.html { redirect_to @family_type, notice: 'Family type was successfully updated.' }
        format.json { render :show, status: :ok, location: @family_type }
      else
        format.html { render :edit }
        format.json { render json: @family_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /family_types/1
  # DELETE /family_types/1.json
  def destroy
    @family_type.destroy
    respond_to do |format|
      format.html { redirect_to family_types_url, notice: 'Family type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family_type
      @family_type = FamilyType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_type_params
      params.require(:family_type).permit(:name)
    end
end

app/helpers/family_types_helper.rb
module FamilyTypesHelper
end

app/views/family_types/_form.html.haml
= form_for @family_type do |f|
  - if @family_type.errors.any?
    #error_explanation
      %h2= "#{pluralize(@family_type.errors.count, "error")} prohibited this family_type from being saved:"
      %ul
        - @family_type.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/family_types/edit.html.haml
%h1 Editing family_type

= render 'form'

= link_to 'Show', @family_type
\|
= link_to 'Back', family_types_path

app/views/family_types/index.html.haml
%h1 Listing family_types

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @family_types.each do |family_type|
      %tr
        %td= family_type.name
        %td= link_to 'Show', family_type
        %td= link_to 'Edit', edit_family_type_path(family_type)
        %td= link_to 'Destroy', family_type, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Family type', new_family_type_path

app/views/family_types/new.html.haml
%h1 New family_type

= render 'form'

= link_to 'Back', family_types_path

app/views/family_types/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @family_type.name

= link_to 'Edit', edit_family_type_path(@family_type)
\|
= link_to 'Back', family_types_path