config/routes.rb
Rails.application.routes.draw do
  resources :bottles
  resources :perfumes
  resources :bottle_types
  resources :perfume_types
  resources :family_types

  get '/', :to => 'static#home'
  root 'static#home'

  namespace :api, defaults: { format: 'json' } do
  	namespace :v1 do
  	  resources :bottles, only: [:create, :update, :show, :index]
      resources :perfumes, only: [:create, :update, :show, :index]
      resources :bottle_types, only: [:create, :update, :show, :index]
      resources :perfume_types, only: [:create, :update, :show, :index]
      resources :family_types, only: [:create, :update, :show, :index]
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/api/v1/perfume_types_controller.rb
module API
  module V1
    class PerfumeTypesController < ApiController
      before_action :set_perfume_type, only: [:show, :edit, :update, :destroy]

      # GET /perfume_types
      # GET /perfume_types.json
      def index
        @perfume_types = PerfumeType.all
      end

      # GET /perfume_types/1
      # GET /perfume_types/1.json
      def show
      end

      # GET /perfume_types/new
      def new
        @perfume_type = PerfumeType.new
      end

      # GET /perfume_types/1/edit
      def edit
      end

      # POST /perfume_types
      # POST /perfume_types.json
      def create
        @perfume_type = PerfumeType.new(perfume_type_params)

        respond_to do |format|
          if @perfume_type.save
            format.html { redirect_to @perfume_type, notice: 'Perfume type was successfully created.' }
            format.json { render :show, status: :created, location: @perfume_type }
          else
            format.html { render :new }
            format.json { render json: @perfume_type.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /perfume_types/1
      # PATCH/PUT /perfume_types/1.json
      def update
        respond_to do |format|
          if @perfume_type.update(perfume_type_params)
            format.html { redirect_to @perfume_type, notice: 'Perfume type was successfully updated.' }
            format.json { render :show, status: :ok, location: @perfume_type }
          else
            format.html { render :edit }
            format.json { render json: @perfume_type.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /perfume_types/1
      # DELETE /perfume_types/1.json
      def destroy
        @perfume_type.destroy
        respond_to do |format|
          format.html { redirect_to perfume_types_url, notice: 'Perfume type was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_perfume_type
          @perfume_type = PerfumeType.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def perfume_type_params
          params.require(:perfume_type).permit(:name)
        end
    end
  end
end

app/controllers/perfume_types_controller.rb
class PerfumeTypesController < ApplicationController
  before_action :set_perfume_type, only: [:show, :edit, :update, :destroy]

  # GET /perfume_types
  # GET /perfume_types.json
  def index
    @perfume_types = PerfumeType.all
  end

  # GET /perfume_types/1
  # GET /perfume_types/1.json
  def show
  end

  # GET /perfume_types/new
  def new
    @perfume_type = PerfumeType.new
  end

  # GET /perfume_types/1/edit
  def edit
  end

  # POST /perfume_types
  # POST /perfume_types.json
  def create
    @perfume_type = PerfumeType.new(perfume_type_params)

    respond_to do |format|
      if @perfume_type.save
        format.html { redirect_to @perfume_type, notice: 'Perfume type was successfully created.' }
        format.json { render :show, status: :created, location: @perfume_type }
      else
        format.html { render :new }
        format.json { render json: @perfume_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perfume_types/1
  # PATCH/PUT /perfume_types/1.json
  def update
    respond_to do |format|
      if @perfume_type.update(perfume_type_params)
        format.html { redirect_to @perfume_type, notice: 'Perfume type was successfully updated.' }
        format.json { render :show, status: :ok, location: @perfume_type }
      else
        format.html { render :edit }
        format.json { render json: @perfume_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perfume_types/1
  # DELETE /perfume_types/1.json
  def destroy
    @perfume_type.destroy
    respond_to do |format|
      format.html { redirect_to perfume_types_url, notice: 'Perfume type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perfume_type
      @perfume_type = PerfumeType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def perfume_type_params
      params.require(:perfume_type).permit(:name)
    end
end

app/helpers/perfume_types_helper.rb
module PerfumeTypesHelper
end

app/views/perfume_types/_form.html.haml
= form_for @perfume_type do |f|
  - if @perfume_type.errors.any?
    #error_explanation
      %h2= "#{pluralize(@perfume_type.errors.count, "error")} prohibited this perfume_type from being saved:"
      %ul
        - @perfume_type.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/perfume_types/edit.html.haml
%h1 Editing perfume_type

= render 'form'

= link_to 'Show', @perfume_type
\|
= link_to 'Back', perfume_types_path

app/views/perfume_types/index.html.haml
%h1 Listing perfume_types

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @perfume_types.each do |perfume_type|
      %tr
        %td= perfume_type.name
        %td= link_to 'Show', perfume_type
        %td= link_to 'Edit', edit_perfume_type_path(perfume_type)
        %td= link_to 'Destroy', perfume_type, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Perfume type', new_perfume_type_path

app/views/perfume_types/new.html.haml
%h1 New perfume_type

= render 'form'

= link_to 'Back', perfume_types_path

app/views/perfume_types/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @perfume_type.name

= link_to 'Edit', edit_perfume_type_path(@perfume_type)
\|
= link_to 'Back', perfume_types_path